backends:
  # simulation backends - numpy is available by default
  - name: qibojit
    class: JITCustomBackend
    from: qibojit.custom_operators
    minimum_version: 0.0.4.dev0

  - name: qibotf
    class: TensorflowCustomBackend
    from: qibotf.custom_operators
    minimum_version: 0.0.4.dev0

  - name: tensorflow
    class: TensorflowBackend
    from: qibo.backends.tensorflow
    minimum_version: 2.2.0

  # hardware backends
  - name: qiboicarusq
    class: IcarusQBackend
    from: qibo.backends.hardware
    minimum_version: 0.0.1.dev0
    is_hardware: True

# default active backend after importing all modules
default: qibojit
