[tool.pylint.master]

exit-zero = true
errors-only = true

[tool.pylint.reports]

# Available formats are:
# text, parseable, colorized, json and msvs (visual studio).
output-format = "colorized"

[tool.pytest.ini_options]

python_files = ['test_*.py']
python_functions = ['test_*']
testpaths = ['src/qibo/tests/']
addopts = [
    '--cov=qibo',
    '--cov-report=xml',
    '--pyargs qibo',
    '--durations=60'
]
