[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "qibo"
version = "0.1.12.dev0"
description = "A framework for quantum computing with hardware acceleration."
authors = ["The Qibo team"]
license = "Apache License 2.0"
readme = "README.md"
homepage = "https://qibo.science/"
repository = "https://github.com/qiboteam/qibo/"
documentation = "https://qibo.science/docs/qibo/stable"
keywords = []
classifiers = [
  "Programming Language :: Python :: 3",
  "Topic :: Scientific/Engineering :: Physics",
]
packages = [{ include = "qibo", from = "src" }]
include = ["*.out", "*.yml"]

[tool.poetry.dependencies]
python = ">=3.7.2,<3.11"
scipy = "^1.7.3"
sympy = "^1.9.0"
cma = "^3.3.0"
joblib = "^1.2.0"
matplotlib = "^3.5.3"
psutil = "^5.9.4"
tabulate = "^0.9.0"
nlopt = "^2.7.1"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx = "^4.3.0"
furo = "^2022.9.29"
recommonmark = "^0.7.1"
sphinxcontrib-bibtex = "^2.5.0"
sphinx-markdown-tables = "^0.0.15"
nbsphinx = "^0.8.12"
ipython = "^7.17.0"

[tool.poetry.group.tests]
optional = true

[tool.poetry.group.tests.dependencies]
pytest = "^7.2.1"
cirq = "^0.14.1"
ply = "^3.11"
scikit-learn = "^1.0.2"
dill = "^0.3.6"
pytest-cov = "^4.0.0"
pylint = "^2.16.2"
qibojit = { git = "https://github.com/qiboteam/qibojit" }
tensorflow = { version = "^2.11.0", markers = "sys_platform == 'linux' or sys_platform == 'darwin'" }
tensorflow-intel = { version = "^2.11.0", markers = "sys_platform == 'win32'" }

[tool.poe.tasks]
test = "pytest"
lint = "pylint src --errors-only"
lint-warnings = "pylint src --exit-zero"
docs = "make -C doc html"
docs-clean = "make -C doc clean"
test-docs = "make -C doc doctest"

[tool.pylint.reports]
output-format = "colorized"

[tool.pytest.ini_options]
testpaths = ['tests/']
filterwarnings = ['ignore::RuntimeWarning']
addopts = [
  '--cov=qibo',
  '--cov-append',
  '--cov-report=xml',
  '--cov-report=html',
  '--durations=60',
]
