[tool.pylint.master]
output-format = "colorized"

[tool.pylint.reports]

# Available formats are:
# text, parseable, colorized, json and msvs (visual studio).
output-format = "colorized"

[tool.pytest.ini_options]

testpaths = ['tests/']
filterwarnings = ['ignore::RuntimeWarning']
addopts =  [ '--pyargs qibo', '--cov=qibo', '--cov-report=xml', '--durations=60']
