[tool.pylint.master]
<<<<<<< HEAD

exit-zero = true
errors-only = true
=======
output-format = "colorized"
>>>>>>> eeaf05571b873a792b27e0631ddfba6f0ac08810

[tool.pylint.reports]

# Available formats are:
# text, parseable, colorized, json and msvs (visual studio).
output-format = "colorized"

[tool.pytest.ini_options]

testpaths = ['src/qibo/tests/']
filterwarnings = ["ignore::RuntimeWarning"]
addopts = [
    '--cov=qibo',
    '--cov-report=xml'
]
