[tool.pylint.master]

exit-zero = true
errors-only = true

[tool.pylint.reports]

# Available formats are:
# text, parseable, colorized, json and msvs (visual studio).
output-format = "colorized"

[tool.pytest.ini_options]

testpaths = ['src/qibo/tests/']
filterwarnings = ["ignore::RuntimeWarning"]
addopts = [
    '--cov=qibo',
    '--cov-report=xml'
]
