# A single CI script with github workflow
name: Build wheels and deploy

on:
  push:
  release:
    types:
      - published

jobs:
  call-reusable-workflow-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9, '3.10']
    uses: qiboteam/workflows/deploy-pip.yml@migration
    with: 
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}