# A single CI script with github workflow
name: Tests

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9, '3.10']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install pytest-cov
        pip install .[tests,docs]
        pip install git+https://github.com/qiboteam/qibojit
        pip install tensorflow
    - name: Install cupy on linux
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
        sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
        sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /"
        sudo apt-get update
        sudo apt install cuda-11-6
        pip install cupy-cuda116
    - name: Test with pylint
      run: |
        pip install pylint
        pylint src -E -d E1123,E1120
    - name: Test with pytest core
      run: |
        pytest src/qibo/tests/ --skip-parallel --cov=qibo --cov-report=xml --pyargs qibo --durations=60
    - name: Test documentation examples
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt install pandoc
        make -C doc doctest
    - name: Test examples
      if: startsWith(matrix.os, 'ubuntu') && matrix.python-version == '3.9'
      run: |
        OMP_NUM_THREADS=1 pytest examples/
    - name: Upload coverage to Codecov
      if: startsWith(matrix.os, 'ubuntu')
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
